### PR TITLE
Issue 36 more advance search

### PR DESCRIPTION
**Pull request by ninjahoahong**
I have apply the SearchView widget and apply the simple search by summary for the NoteBook. Now the results will be all the notes of the user, and the results view update when the text query is changed.

### CODE REVIEW

**Comment by proninyaroslav** [comment]
@ninjahoahong 
You can attach result screenshots?

**Comment by ninjahoahong** [comment]
Hi @proninyaroslav. These are some screenshots.

device-2016-01-21-173830
device-2016-01-21-173920
device-2016-01-21-174246

**Comment by proninyaroslav** [comment]
@ninjahoahong 
Excellent work. It would be nice to add hint text in the search box, something like "Search"

**Comment by ninjahoahong** [comment]
@proninyaroslav thank you. I added the hint to the search view now.

**Pull request merged**
